#include "stm8s_uart1.h"
void vUART_Config(void)
{
  //CLK->PCKENR1 |= CLK_PCKENR1_UART1; //ENABLE CLOCKING
  //UART1->BRR1 = 0x68;
  //UART1->BRR2 = 0x02;
  //UART1->CR2 |= UART1_CR2_REN | UART1_CR2_TEN;
  UART1_Init(9600, UART1_WORDLENGTH_8D, UART1_STOPBITS_1, UART1_PARITY_NO, UART1_SYNCMODE_CLOCK_DISABLE, UART1_MODE_TXRX_ENABLE);
  //UART1_ITConfig(UART1_IT_RXNE, ENABLE);
  UART1_Cmd(ENABLE);
}